// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Waybill.EntityFrameworkCore.Schema;

#nullable disable

namespace Waybill.EntityFrameworkCore.Schema.Migrations
{
    [DbContext(typeof(WaybillSchemaContext))]
    partial class WaybillSchemaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("waybill")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Waybill.EntityFrameworkCore.Schema.InboxRow", b =>
                {
                    b.Property<string>("Handler")
                        .HasColumnType("text")
                        .HasColumnName("handler");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.HasKey("Handler", "MessageId")
                        .HasName("pk_inbox");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_inbox_processed_at");

                    b.ToTable("inbox", "waybill");
                });

            modelBuilder.Entity("Waybill.EntityFrameworkCore.Schema.InstanceRow", b =>
                {
                    b.Property<string>("Owner")
                        .HasColumnType("text")
                        .HasColumnName("owner");

                    b.Property<DateTimeOffset>("HeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("heartbeat_at");

                    b.HasKey("Owner")
                        .HasName("pk_outbox_instances");

                    b.ToTable("outbox_instances", "waybill");
                });

            modelBuilder.Entity("Waybill.EntityFrameworkCore.Schema.KeyRow", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.HasKey("Key")
                        .HasName("pk_outbox_keys");

                    b.ToTable("outbox_keys", "waybill");

                    b.HasAnnotation("Npgsql:StorageParameter:fillfactor", 80);
                });

            modelBuilder.Entity("Waybill.EntityFrameworkCore.Schema.OutboxRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<string>("DlqReason")
                        .HasColumnType("text")
                        .HasColumnName("dlq_reason");

                    b.Property<long>("Fence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("fence");

                    b.Property<string>("Headers")
                        .HasColumnType("jsonb")
                        .HasColumnName("headers");

                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<int>("KeyHash")
                        .HasColumnType("integer")
                        .HasColumnName("key_hash");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.PrimitiveCollection<string[]>("LockKeys")
                        .HasColumnType("text[]")
                        .HasColumnName("lock_keys");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Owner")
                        .HasColumnType("text")
                        .HasColumnName("owner");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<string>("ReleasedBy")
                        .HasColumnType("text")
                        .HasColumnName("released_by");

                    b.Property<long?>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_outbox_claimable")
                        .HasFilter("status IN ('pending', 'claimed')");

                    b.HasIndex("Key")
                        .HasDatabaseName("ix_outbox_blocked_keys")
                        .HasFilter("status = 'dlq' AND sequence IS NOT NULL");

                    b.HasIndex("Key", "Sequence")
                        .HasDatabaseName("ix_outbox_key_sequence")
                        .HasFilter("sequence IS NOT NULL AND status IN ('pending', 'claimed', 'dlq')");

                    b.ToTable("outbox", "waybill", t =>
                        {
                            t.HasCheckConstraint("ck_outbox_status", "status IN ('pending', 'claimed', 'published', 'dlq', 'released')");
                        });
                });

            modelBuilder.Entity("Waybill.EntityFrameworkCore.Schema.PartitionRow", b =>
                {
                    b.Property<int>("Partition")
                        .HasColumnType("integer")
                        .HasColumnName("partition");

                    b.Property<long>("Epoch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("epoch");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<string>("Owner")
                        .HasColumnType("text")
                        .HasColumnName("owner");

                    b.HasKey("Partition")
                        .HasName("pk_outbox_partitions");

                    b.ToTable("outbox_partitions", "waybill");
                });

            modelBuilder.Entity("Waybill.EntityFrameworkCore.Schema.SettingsRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<TimeSpan>("PartitionLease")
                        .HasColumnType("interval")
                        .HasColumnName("partition_lease");

                    b.Property<int>("Partitions")
                        .HasColumnType("integer")
                        .HasColumnName("partitions");

                    b.HasKey("Id")
                        .HasName("pk_settings");

                    b.ToTable("settings", "waybill", t =>
                        {
                            t.HasCheckConstraint("ck_settings_single_row", "id = 1");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
